name: Unzip and Commit ZIP Contents

on:
  workflow_dispatch:
  push:
    paths:
      - 'download (2).zip'

jobs:
  unzip_and_commit:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Unzip file
        run: |
          unzip -o "download (2).zip" -d .

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add .
          git status
          git diff --cached --quiet || git commit -m "Unzip and commit contents of download (2).zip [skip ci]"
          git push "https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" HEAD:${GITHUB_REF#refs/heads/}
